# Generated by Django 4.0.3 on 2022-03-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTitle', models.CharField(max_length=100, verbose_name='Event Title')),
                ('frequency', models.PositiveSmallIntegerField(choices=[(0, 'One-off Event'), (1, 'Monthly'), (2, 'Every Other Week'), (4, 'Weekly')], default=4, verbose_name='Event Frequency')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('type', models.CharField(choices=[('HH', 'Happy Hour'), ('SP', 'Student Special'), ('HS', 'Holiday Special')], max_length=100, verbose_name='Event Type')),
                ('description', models.TextField(max_length=2000, verbose_name='Event Description')),
                ('photos', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=100, verbose_name='Business or Location Name')),
                ('listing', models.URLField(verbose_name='Google Maps Listing')),
                ('website', models.URLField(verbose_name='Website')),
            ],
        ),
    ]
