# Generated by Django 4.0.3 on 2022-03-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(max_length=100, verbose_name='Start and End time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('HH', 'Happy Hour'), ('SP', 'Student Special'), ('OT', 'Other')], default='HH', max_length=100, null=True, verbose_name='Event Type'),
        ),
    ]
