# Generated by Django 4.0.3 on 2022-04-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_alter_event_time_alter_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dayOfWeek',
            field=models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], default='MO', max_length=10, verbose_name='Day of Week'),
        ),
        migrations.AlterField(
            model_name='event',
            name='frequency',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Weekly')], default=4, verbose_name='Event Frequency'),
        ),
    ]
