# Generated by Django 4.0.3 on 2022-04-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_alter_event_active_alter_event_dayofweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('O', 'Other'), ('R', 'Restaurant'), ('B', 'Bar')], default='B', max_length=10, null=True, verbose_name='Type of Establishment'),
        ),
    ]
