# Generated by Django 4.0.2 on 2022-04-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='picture',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
