# Generated by Django 4.0.3 on 2022-05-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_location_address_location_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('HH', 'Happy Hour'), ('FS', 'Food Special'), ('DS', 'Drink Special'), ('SP', 'Student Special'), ('AC', 'Activity'), ('OT', 'Other')], default='HH', max_length=100, null=True, verbose_name='Event Type'),
        ),
    ]
