# Generated by Django 4.0.3 on 2022-05-10 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0007_alter_event_type'),
        ('Events', '0007_fav'),
    ]

    operations = [
    ]
