# Generated by Django 4.0.2 on 2022-03-30 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=100, verbose_name='Business or Location Name')),
                ('listing', models.URLField(verbose_name='Google Maps Listing')),
                ('website', models.URLField(null=True, verbose_name='Business or Location Website')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTitle', models.CharField(max_length=100, verbose_name='Event Title')),
                ('frequency', models.PositiveSmallIntegerField(choices=[(0, 'One-off Event'), (1, 'Monthly'), (2, 'Every Other Week'), (4, 'Weekly')], default=4, verbose_name='Event Frequency')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('type', models.CharField(choices=[('HH', 'Happy Hour'), ('SP', 'Student Special'), ('OT', 'Other')], default='HH', max_length=100, null=True, verbose_name='Event Type')),
                ('description', models.TextField(max_length=2000, null=True, verbose_name='Event Description')),
                ('time', models.CharField(max_length=100, verbose_name='Start and End time')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.location')),
            ],
        ),
    ]
