# Generated by Django 4.0.3 on 2022-04-06 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_location_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.DeleteModel(
            name='phoneSignup',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
