# Generated by Django 3.2.5 on 2021-07-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(blank=True, max_length=90, null=True)),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True, unique=True)),
                ('address', models.TextField()),
                ('img', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('bd', models.TextField(blank=True, null=True)),
                ('ba', models.TextField(blank=True, null=True)),
                ('lotSize', models.TextField(blank=True, null=True)),
                ('sqFt', models.TextField(blank=True, null=True)),
                ('companyListed', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
