name: PY CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: install dependencies
        run:
          sudo apt install -y build-essential
          pip3 install -r requirements.txt
      - name: Run Tests
        run: python3 manage.py test